name: scryfall-archiver

services:
  scryfall-archiver:
    container_name: scryfall-archiver
    command: ['/scryfall-archiver']
    image: scryfall-archiver:latest
    build:
      context: ../src
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - /YOUR/DATA/PATH:/data
    environment:
      SA_DATA_DIR: /data
      SA_ARCHIVE_SCHEDULE: "0 2 1 * * * *"
      SA_BACKUP_SMALL_IMAGE: false
      SA_BACKUP_NORMAL_IMAGE: false
      SA_BACKUP_LARGE_IMAGE: false
      SA_BACKUP_PNG_IMAGE: true
      SA_BACKUP_ART_CROP_IMAGE: false
      SA_BACKUP_BORDER_CROP_IMAGE: false
      SA_VERSION: "1.0.0"
      RUST_LOG: info
    healthcheck:
      disable: false