name: scryfall-archiver

services:
  nrm-server:
    container_name: scryfall-archiver
    command: ['/scryfall-archiver']
    image: scryfall-archiver:latest
    build:
      context: ../src
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - C:/Users/Tormak/Desktop/NRM:/data
    env_file:
      - .env
    environment:
      SA_DATA_DIR: /data
      SA_ARCHIVE_SCHEDULE: "0 0 3 * * * *"
      SA_VERSION: "1.0.0"
      SA_BACKUP_SMALL_IMAGE: false
      SA_BACKUP_NORMAL_IMAGE: false
      SA_BACKUP_LARGE_IMAGE: false
      SA_BACKUP_PNG_IMAGE: true
      SA_BACKUP_ART_CROP_IMAGE: false
      SA_BACKUP_BORDER_CROP_IMAGE: false
      RUST_LOG: info
    healthcheck:
      disable: false